#!/usr/bin/env perl

use Mojolicious::Lite;
use Mojo::JSON qw(decode_json);
use Mojo::UserAgent;
use Mojo::File;

use DateTime;
use Readonly;
use autodie;

use lib 'lib';
use Mojo::Base 'XlsChart';

plugin 'RenderFile';
plugin AssetPack => {pipes => [qw(Vuejs JavaScript Css)]};

app->asset->process(
  'app.css' => qw(
    https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css
    /css/bootstrap.css 
  ),
);

app->asset->process(
  "app.js" => qw(
    https://cdn.jsdelivr.net/npm/vue/dist/vue.js
    /js/component.js
  ),
);

Readonly::Hash my %config => (
  url      => 'http://exfidefortis.net/apps/covid',
  sheet    => 'covid',
  chart    => {
  	xls_name => 'covid.xlsx',
  	y_axis_name => 'date',
  	x_axis_name => 'no of cases',
  	title  => 'covid Cluj county',
  	height => 576,
  	width  => 720,
  },
);

helper mojo_file => sub { Mojo::File->new(); };
helper date      => sub { DateTime->now()->date(); };
helper ua        => sub { Mojo::UserAgent->new(); };
helper xls_chart => sub { XlsChart->new( config => $config{chart} ); };

get '/api/v1/download/covid' => sub {
  my $c = shift;

  my $new_file = sprintf( "saved_data_%s.json", $c->date() );

  foreach my $file ( _get_old_json_files($new_file) ) {
    $c->mojo_file()->path($file)->remove();
  }

  unless ( -e $new_file ) {
    print "Fetching fresh json data\n";

    my $tx = $c->ua()->get( $config{'url'} );

    unless ( $tx->result->is_success ) {
      die 'Could not make request';
    }

    $tx->result->save_to( $new_file );
  }

  my $data = decode_json( $c->mojo_file()->path($new_file)->slurp() );
  
  my $xls_object = $c->xls_chart();  
  foreach my $data_set_name (keys %{$data} ) {
  	$xls_object->make_array_of_arrays( $data->{$data_set_name} )->write_chart( $data_set_name );
  }
  
  $c->render_file( 'filepath' => $config{chart}->{'xls_name'} );
};


get '/covid/chart' => sub {
  my $c = shift;
  $c->render(template => 'index');
};

post '/covid/chart' => sub {
  my $c = shift;
  $c->render( json => { hello => 'bender' });
};


sub _get_old_json_files {
  my $new_file  = shift;
  my $mojo_file = shift;

  opendir my $dir, '.';
  my @old_files = grep { $_ =~ /\.json/ && $_ !~ /$new_file/ } readdir($dir);
  closedir $dir;

  return @old_files;

}

app->start;

__DATA__
@@ /css/bootstrap.css
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Bare - Start Bootstrap Template</title>

@@ /js/component.js

var app = new Vue({
  el: "#app",
    data: {
        message1: "Hello, World! ",
        message2: "Vue"
    }
})

@@ index.html.ep
% layout 'default';

@@ layouts/default.html.ep
<!DOCTYPE html>
<html lang="en">
<head>
  %= asset "app.css"
</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <div class="container">
      <a class="navbar-brand" href="#">Start Bootstrap</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h1 class="mt-5">A Bootstrap 4 Starter Template</h1>
        <p class="lead">Complete with pre-defined file paths and responsive navigation!</p>
        <div id="app">
          <p v-html="message1"></p>
        </div>
        <ul class="list-unstyled">
          <li>Bootstrap 4.5.0</li>
          <li>jQuery 3.5.1</li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript -->
  
%= asset "app.js"
</body>

</html>
