requires 'Mojolicious';
requires 'Mojo::JSON';
requires 'Mojo::UserAgent';
requires 'Mojo::File';
requires 'Mojolicious::Plugin::RenderFile';
requires 'DateTime';
requires 'Readonly';
requires 'Mojo::Base';
requires 'Excel::Writer::XLSX';
